### ISSUE TITLE
Documentação Sprint 06

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#106]
### Descrição:
Documentar o planejamento e o resultado da sprint 06

### Tarefas:

- [x]  Atuzalizar documentos pendentes 
- [x] Organização para a entrega da realese 1
- [x] Gravar vídeo de apresentação do projeto
- [x] Gravar vídeo time A
- [x] Gravar vídeo time B

### Critérios de aceitação:

- [x] Documentações dos times A e B
- [x] Documentos revisados

**Comment by laisramos123** [comment]
A documentações da sprint 06 foram entregues junto à Release 01
