### ISSUE TITLE
Elaborar Modelo Canvas

### ISSUE THREAD

**Issue by ahbreu** [fga-eps-mds/2021.2-Sigaa-Plus#115]
### Descrição:
Elaborar documento que descreve a forma como a extensão irá operar e gerar valor no mercado listando seus principais fluxos, processos e segmentos.

### Tarefas:

- [x]  Elaborar modelo canvas

### Critérios de aceitação:

- [x] Revisar modelo canvas

**Comment by ahbreu** [comment]
Este foi o [Modelo Canvas](https://github.com/fga-eps-mds/2021.2-Sigaa-Plus/files/8181972/Modelo.Canvas.pdf) feito na plataforma do [SEBRAE](https://www.sebraecanvas.com/).

**Comment by laisramos123** [comment]
O modelo foi revisado e precisará fazer uma modificação em relação às fontes de receita. As fontes irão ser captadas à partir de uma parceria entre a  repartição Diretoria de Contabilidade e Finanças (DCF) -o órgão responsável pela coordenação da contabilidade orçamentária, financeira e patrimonial da Fundação Universidade de Brasília (FUB) - e a equipe.
