### ISSUE TITLE
Implementação da lista de presença até o dia 29/03

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#139]
### Descrição:
Implementação da lista de presença das Dailys e reuniões com o time B.

### Tarefas:

- [x] Implementação da tabela

### Critérios de aceitação:
- [x] Aceitação do time

**Comment by GabriellyAssuncao** [comment]
A lista de presença já está sendo utilizada pelo time A
