### ISSUE TITLE
Implementação do template das Dailys

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#140]
### Descrição:
Implementação do template das Dailys, as mesmas serão feitas todos os dias da semana.

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x]  Criar tabela de registro de dailys.

### Critérios de aceitação:

- [x] Aceitação pelos membros do grupo

**Comment by laisramos123** [comment]
A tabela se encontra [aqui](https://docs.google.com/spreadsheets/d/1jPrgnsRnUocsf_TVaLdnGFO64R4AZrgTcXtn2OW93nY/edit#gid=0)

**Comment by GabriellyAssuncao** [comment]
A metodologia de dailys ja foi implementada pelo time A
