### ISSUE TITLE
planejamento do dojo (Front-End)

### ISSUE THREAD

**Issue by Madu01** [fga-eps-mds/2021.2-Sigaa-Plus#141]
### Descrição:

Será planejado os dojos do Front-End.

### Tarefas:

- [x] Decidir quais tecnologias que serão implementadas no dojo
- [x] Organizar quais são os responsáveis para a realização de cada dojo
- [x] Decidir o formato de como será passado o conteúdo 
- [x] Decidir o prazo de entrega

### Critérios de aceitação:

- [x] Realizar uma reunião

**Comment by Madu01** [comment]
Na reunião decidimos as tecnologias e os responsáveis:
Plugin para o Google Chrome - Maria Marques
HTML/CSS - Beatriz 
JavaScript - Luiz
Vue.js - Maria Eduarda B. e Bruno

**Comment by eng-Bruno** [comment]
Formato da apresentação do conteúdo: 
- Vídeo (gravando a voz e a tela)
- Explicar a tecnologia mostrando na prática por meio de um código simples (a ideia é que a pessoa que tenha assistido o vídeo seja capaz de fazer o básico da tecnologia )

**Comment by eng-Bruno** [comment]
Prazo de entrega estipulado pelo time:
* até sábado às 23h59

**Comment by eng-Bruno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/141?planning-poker) with ZenHub @beatrizSO @EduardaSMarques @LuizPettengill @Madu01
