### ISSUE TITLE
dojo front-end (Vue.js)

### ISSUE THREAD

**Issue by Madu01** [fga-eps-mds/2021.2-Sigaa-Plus#142]
### Descrição:

será desenvolvido o dojo front-end (Vue.js).

### Tarefas:

- [x]  Decidir o dia para gravar o vídeo
- [x]  Estudar a tecnologia Vue.js 
- [x]  Fazer um código simples para um melhor entendimento do Vue.js 
- [x]  Gravar o vídeo explicando a tecnologia Vue.js 

### Critérios de aceitação:

- [x] Disponibilizar o vídeo do dojo Vue.js
- [x] Disponibilizar o código do dojo Vue.js

**Comment by Madu01** [comment]
O dia para a gravação:
- sexta às 17h

**Comment by eng-Bruno** [comment]
Material de estudo:
[Youtube](https://www.youtube.com/watch?v=cSa-SMVMGsE&ab_channel=ProgramadoraBordo)

**Comment by eng-Bruno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/142?planning-poker) with ZenHub @beatrizSO @EduardaSMarques @LuizPettengill @Madu01

**Comment by eng-Bruno** [comment]
Link para o vídeo:
[Dojo VueJS](https://drive.google.com/drive/folders/1ut63WY78YcgOZZRj318W_KQDnENrhEO2)

**Comment by Madu01** [comment]
Ah esqueci de falar uma coisa no vídeo "Dojo VueJS (Parte 2)", é sobre a extensão que utilizei no vscode para o código vue, se chama Vetur! 
Os documentos citados no vídeo para a prática do estudo:
Esta disponível em [ambientação](https://vuejs.org/guide/quick-start.html#quick-start), [Tutorial](https://vuejs.org/tutorial/#step-1) e [Doc](https://vuejs.org/guide/introduction.html#introduction)
