### ISSUE TITLE
Documentação Sprint 7 - Time A

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#143]
### Descrição:
Documentar o planejamento e o resultado da sprint 07

### Tarefas:

- [x] Planejamento sprint 07
- [x] Definir prioridade de funcionalidades
- [x] Definir tarefas
- [x] Atualizar README
- [x] Planning Poker
- [x] Atualizar git pages
- [x] Atualizar plano de comunicação
- [x] Resultado sprint 07

### Critérios de aceitação:

- [x] Documentos revisados

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/143?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by HianPraxedes** [comment]
Funções atribuídas para os PO's do Grupo A:
Corrigir e atualizar documentos de visão e requisitos;
Atualizar o git pages;

**Comment by laisramos123** [comment]
Funções atribuídas aos Scrum Masters do Time A: 
Fazer o Planejamento e resultado da Sprint 07

**Comment by GabriellyAssuncao** [comment]
O time A, responsável pelo backend do projeto,  se dividiu da seguinte forma para trabalhar nas funcionalidades dos 2 primeiros requisitos funcionais:
- Vizualizar matérias equivalêntes do curso: @vitormanoel17 @Elios630 @ahbreu 
- Vizualizar disciplinas do fluxo curricular: @GabriellyAssuncao @HianPraxedes  @laisramos123
