### ISSUE TITLE
Dojo das tecnologias Back-end Time A

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#144]
### Descrição:
Dojo sobre as tecnologias que serão utilizadas na implementação do Back-end do projeto. O dojo será dado pelo integrante @vitormanoel17  no dia 09/03 às 18h pela plataforma Discord.

### Tarefas:
- [x] Dojo sobre Javascript, NodeJs ,Pupperteer.

### Critérios de aceitação:
- [x] Atualização do quadro de conhecimentos

**Comment by HianPraxedes** [comment]
Documentações usadas para estudo do ensinamentos do Dojo:
https://pptr.dev/#?product=Puppeteer&version=v13.4.1&show=api-class-browsercontext
http://expressjs.com/
https://masteringbackend.com/posts/web-scraping-with-nodejs-and-puppeteer

**Comment by laisramos123** [comment]
Link para a atualização do quadro de conhecimentos: https://docs.google.com/spreadsheets/d/1tGYGCx97DXlaN50xZIgqbM9cjN2Hu5pC0yUwO7KhmUk/edit?usp=sharing

**Comment by vitormanoel17** [comment]
Dojo realizado com sucesso, utilizando exemplos práticos e teóricos, apoiados nas referências já listadas acima
