### ISSUE TITLE
Template para as Dailys - Time B

### ISSUE THREAD

**Issue by Madu01** [fga-eps-mds/2021.2-Sigaa-Plus#145]
### Descrição:
será definido o template para as Dailys.

### Tarefas:

- [x]  decidir o template para as dailys

### Critérios de aceitação:

- [x] disponibilização do link para o acesso do template

**Comment by Madu01** [comment]
No momento decidimos utilizar esse template:

- disponível em [Template-timeB](https://docs.google.com/spreadsheets/d/11dNcmrSCw1ZvFHj75GwtfAsah41IydpKwFSdNp9eowg/edit?usp=sharing)

Mas ficamos de testar o google forms e caso o teste saia como o esperado, migramos dessa template atual para uma nova implementada no google forms.

**Comment by eng-Bruno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/145?planning-poker) with ZenHub @beatrizSO @EduardaSMarques @LuizPettengill @Madu01
