### ISSUE TITLE
Dojo front-end (HTML/CSS)

### ISSUE THREAD

**Issue by beatrizSO** [fga-eps-mds/2021.2-Sigaa-Plus#146]
### Descrição:
Dojo das tecnologias front-end HTML e CSS.

### Tarefas:

- [x]  Estudar sobre as tecnologias
- [x] Preparar material para apresentação
- [x] Gravar vídeo

### Critérios de aceitação:

- [x] Disponibilizar vídeo 
- [x] Disponibilizar código utilizado

**Comment by eng-Bruno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/146?planning-poker) with ZenHub @beatrizSO @EduardaSMarques @LuizPettengill @Madu01
