### ISSUE TITLE
Reunião para escalonamento de prioridades e divisão de tarefas do Back-end

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#147]
### Descrição:
Reunião para a divisão dos processos e tarefas e escalonamento de prioridades do Back-end de acordo com o Documento de Visão.

### Tarefas:
- [x]  Escalonar prioridades das funcionalidades de acordo com o Documento de Visão
- [x] Divisão de tarefas e processos com o time.

### Critérios de aceitação:
- [x] Todos do time deverão fazer votação
- [x] As decisões deverão ser documentadas e comentadas na issue em questão

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/147?planning-poker) with ZenHub @ahbreu @GabriellyAssuncao @vitormanoel17 @HianPraxedes @Elios630

**Comment by GabriellyAssuncao** [comment]
O time A, responsável pelo backend do projeto, se dividiu da seguinte forma para trabalhar nas funcionalidades dos 2 primeiros requisitos funcionais:

- Vizualizar matérias equivalêntes do curso: @vitormanoel17 @Elios630 @ahbreu
- Vizualizar disciplinas do fluxo curricular: @GabriellyAssuncao @HianPraxedes @laisramos123

**Comment by laisramos123** [comment]
Divisão feita com sucesso!
