### ISSUE TITLE
Atualização simples do Readme

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#149]
### Descrição:
Inserção dos comandos para o download do ambiente de desenvolvimento do time.

### Tarefas:
- [x]  Inserção de documentos

### Critérios de aceitação:
- [x] Revisão por um membro do grupo e feedback do revisor na issue em questão.

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/149?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by vitormanoel17** [comment]
Atualizando realizada, pendente de confirmação e revisão para que possa ser realizado o merge

**Comment by GabriellyAssuncao** [comment]
O documento está de acordo com a proposta.

**Comment by GabriellyAssuncao** [comment]
O documento está de acordo com a proposta.
