### ISSUE TITLE
Atualização do Git Pages do projeto

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#151]
### Descrição:
Inserção de alguns documentos pendentes no Github Pages

### Tarefas:
- [x]  Inserção de documentos
- [x] Revisão de possíveis erros na documentação já presente na página

### Critérios de aceitação:
- [ ] Revisão por outro membro do grupo e comentário do mesmo na issue me questão e/ou no pull-request

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/151?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by HianPraxedes** [comment]
Atualizado com os documento que temos até o momento
