### ISSUE TITLE
Atualização do plano de comunicação do Projeto

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#152]
### Descrição:
Atualização do plano de comunicação do projeto com a inserção dos horários e dias das Dailys e  dos novos horários das reuniões com o Time B, além de também inserir os canais utilizados para tais e o tipo de informação tratado em cada canal.

### Tarefas:
- [x] Inserção dos horários e dias das Dailys e  dos novos horários das reuniões com o Time B;
- [x] Inserção dos canais utilizados para as reuniões  
- [x] Inserção do tipo de informação tratado em cada canal.

### Critérios de aceitação:
- [x] O documento deverá ser revisado e o revisor deverá dar o seu feedback na issue em questão e/ou no pull request.

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/152?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by Elios630** [comment]
- "Inserção dos horários e dias das Dailys e dos novos horários das reuniões com o Time B;"
Atualização do "Cronograma de encontros" em "DocumentoDeMetodologia"

- "inserção dos canais utilizados para as reuniões" e "Inserção do tipo de informação tratado em cada canal."
Criação do documento "DocumentoDeComunicação"

**Comment by GabriellyAssuncao** [comment]
Os documentos foram revisados e aceitos no pull request.
