### ISSUE TITLE
Dojo do Plug-in 

### ISSUE THREAD

**Issue by EduardaSMarques** [fga-eps-mds/2021.2-Sigaa-Plus#154]
### Descrição:
Dojo sobre a Extensões do Google Chrome 

### Tarefas:

- [x]  Estudar sobre a criação de extensões 
- [x] Preparar material de apresentação 
- [x] Gravação do vídeo com o conteúdo 

### Critérios de aceitação:

- [x] Disponibilizar vídeo 
- [x] Disponibilizar códigos utilizados

**Comment by Madu01** [comment]
Esse dojo está disponível em [Dojos_Front-End](https://drive.google.com/drive/folders/1ueHzVDcz1AANw5-w2gPKww63iV4KDYnO?usp=sharing)
