### ISSUE TITLE
Dojo front-end (JavaScript)

### ISSUE THREAD

**Issue by LuizPettengill** [fga-eps-mds/2021.2-Sigaa-Plus#155]
### Descrição:
Nessa issue sera desenvolvido o dojo de JavaScript.

### Tarefas:

- [x] Decidir ferramenta para gravar o vídeo
- [x]  Estudar a tecnologia
- [x]  Praticar a tecnologia
- [x]  Gravar o vídeo explicando a instalação e como utilizar o JavaScript

### Critérios de aceitação:

- [x] Disponibilizar o vídeo do dojo JavaScript
- [x] Disponibilizar o código do dojo JavaScript

**Comment by LuizPettengill** [comment]
Material de estudo 
[Youtube](https://www.youtube.com/watch?v=PkZNo7MFNFg)

**Comment by LuizPettengill** [comment]
Ferramenta de gravação - OBS Studio

**Comment by LuizPettengill** [comment]
Dojo de JavaScript
[Video](https://drive.google.com/file/d/1hKSrkzu704kluN_riRUFKpxeGy-udCm7/view?usp=sharing)
[Codigo](https://drive.google.com/file/d/1MhE40miaaXIG4h5qzyWD_S_ozFwaZjvH/view)

**Comment by Madu01** [comment]
Esse dojo junto com todos os dojos do front-end estão disponíveis em [Dojos_Font-End](https://drive.google.com/drive/folders/1ueHzVDcz1AANw5-w2gPKww63iV4KDYnO?usp=sharing)
