### ISSUE TITLE
Pareamento subgrupo 01

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#166]
### Descrição:
Pareamento do subgrupo 1 para  construção de funcionalidade **RF01**: Permitir que o aluno verifique as equivalências das matérias no SIGAA

### Tarefas:
- [x]  Definir estratégias de para a construção de funcionalidade RF01: Permitir que o aluno verifique as equivalências das matérias no SIGAA

### Critérios de aceitação:

- [x] Realizar reunião para definir estratégias

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/166?planning-poker) with ZenHub @vitormanoel17 @ahbreu @Elios630

**Comment by vitormanoel17** [comment]
Foi decidido que a evolução do código do arquivo webscraping.js será realizado por: @vitormanoel17 
e a criação das rotas para a api, com os dados das matérias equivalentes, será realizado por: @ahbreu  @Elios630
