### ISSUE TITLE
Pareamento subgrupo 02

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#167]
### Descrição:
 Pareamento do subgrupo 2 para construção de funcionalidade **RF02:** Permitir a consulta de fluxo 

### Tarefas:
- [x] Definir estratégias de para a construção de funcionalidade  **RF02:** Permitir a consulta de fluxo 

### Critérios de aceitação:

- [x] Realizar reunião para definir estratégias

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/167?planning-poker) with ZenHub @GabriellyAssuncao @HianPraxedes

**Comment by GabriellyAssuncao** [comment]
Reunião realizada no dia 15 de março através do aplicativo discord com todos os responsáveis pela funcionalidade presentes (@HianPraxedes, @GabriellyAssuncao, @laisramos123 ).

**Comment by GabriellyAssuncao** [comment]
Na reunião foi decidido que cada um ficaria responsável por uma parte do código de criação da funcionalidade.
