### ISSUE TITLE
Refinar Protótipo Alta Qualidade

### ISSUE THREAD

**Issue by beatrizSO** [fga-eps-mds/2021.2-Sigaa-Plus#178]
### Descrição:
Refinamento do protótipo de alta fidelidade

### Tarefas:

- [x]  Encontrar o link para o figma
- [x] Realizar ajustes necessários

### Critérios de aceitação:

- [x] Ajustes realizados coerentes
- [x] Revisão dos protótipos

**Comment by EduardaSMarques** [comment]
Refinamento feito e revisado!
