### ISSUE TITLE
Back-end - RF01

### ISSUE THREAD

**Issue by vitormanoel17** [fga-eps-mds/2021.2-Sigaa-Plus#182]
### Descrição:
Realizar ampliação da captura de dados relacionados a equivalência de  matérias, na página pública do SIGAA, a partir do que já foi feito anteriormente. 

### Tarefas:

- [x]  Expandir captura de matérias equivalentes para todos os departamentos da UnB
- [x]  Armazenar dados capturados em um arquivo JSON

### Critérios de aceitação:

- [x] Alterações devem estar no repositório
- [x] Funcionalidade deve ser revisada

**Comment by vitormanoel17** [comment]
Atualizações realizadas, aguardando aprovação do pull request

**Comment by GabriellyAssuncao** [comment]
pull request aceito
