### ISSUE TITLE
Back-end - RF02

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#186]
### Descrição:
Realizar ampliação da captura de dados relacionados a equivalência de  matérias, na página pública do SIGAA, a partir do que já foi feito anteriormente. 

### Tarefas:

- [x]  Iniciar scraping no site do SIGAA
- [x]  Capturar dados referentes aos cursos

### Critérios de aceitação:

- [x] Alterações devem estar no repositório
- [x] Funcionalidade deve ser revisada

**Comment by GabriellyAssuncao** [comment]
Eu @GabriellyAssuncao iniciei o código de scraper e adicionei ao repositório em uma branch reservada para esta funcionalidade.

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/186?planning-poker) with ZenHub @GabriellyAssuncao @HianPraxedes
