### ISSUE TITLE
Review sprint 08 - Time A

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#187]
### Descrição:
Criar documento de resultado da sprint 08

### Tarefas:

- [x]  Resumir o que foi feito na sprint
- [x]  Inserir métricas
- [x] Inserir quadro de conhecimentos atualizado
- [x] Adicionar feedback do scrum master

### Critérios de aceitação:

- [x] Documento revisado

**Comment by laisramos123** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/187?planning-poker) with ZenHub @GabriellyAssuncao
