### ISSUE TITLE
Desenvolvimento da RF02.

### ISSUE THREAD

**Issue by HianPraxedes** [fga-eps-mds/2021.2-Sigaa-Plus#193]
### Descrição:
Dar continuidade ao  desenvolvimento da RF02: já foi feito a parte da funcionalidade que capturava os dados da página dos cursos. Agora é necessário encontrar uma maneira de classificar e/ou organizar esses dados e também de realizar esse procedimento com todos os outros cursos.
### Tarefas:

- [x] Fazer o webScraping das matérias do fluxo de cada curso
- [x] Agrupar por semestre as matérias referentes ao fluxo de cada curso

### Critérios de aceitação:
- [x] O código deve ser testado
- [x] Pull request deve aceito

**Comment by HianPraxedes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/193?planning-poker) with ZenHub @Elios630

**Comment by HianPraxedes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/193?planning-poker) with ZenHub @vitormanoel17

**Comment by RochaCarla** [comment]
A escrita dessa issue está bastante confusa. o escopo não parece estar bem definido.. Isso aumenta a probabilidade de não ser finalizada no ciclo da sprint

**Comment by laisramos123** [comment]
O conteúdo da issue foi modificada de acordo com o requisitado pela professora!
