### ISSUE TITLE
Revisão em busca de refatoração e criação de rotas RF01 

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#198]
### Descrição:
Aprimorar velocidade com o que o Web Scraping é realizado.

### Tarefas:

- [x]  Buscar melhoria na legibilidade e no tempo do código de Scraping

### Critérios de aceitação:

- [x]  Alterações devem estar no repositório
- [x]  Pull request revisado e aceito

**Comment by GabriellyAssuncao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/198?planning-poker) with ZenHub @laisramos123 @ahbreu @Elios630 @vitormanoel17 @HianPraxedes

**Comment by laisramos123** [comment]
Feitas as alterações requisitadas!
