### ISSUE TITLE
Reunião de nivelamento do grupo em relação ao web scraper

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#200]
### Descrição:
Realizar nivelamento do grupo em relação ao web scraper
### Tarefas:

- [x] Realizar reunião

### Critérios de aceitação:
- [x] Quadro de conhecimentos atualizado

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/200?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @vitormanoel17

**Comment by laisramos123** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/200?planning-poker) with ZenHub @HianPraxedes

**Comment by RochaCarla** [comment]
Além do treinamento, aloquem issues de web scraping pra todas as duplas, para que consolidar o conhecimento nessa sprint. É muito pouco trabalho somente o treinamento.

**Comment by GabriellyAssuncao** [comment]
A reunião foi realizada quinta-feira dia 24/03/2022 via chamada no Discord, com todos os integrantes presentes. Onde cada integrante:
1. Demonstrou e explicou o que fez no código
2. Falou que havia entendido no código do colega
3. Obteve eventuais dúvidas respondidas

**Comment by GabriellyAssuncao** [comment]
Quadro de conhecimentos atualizado: https://docs.google.com/spreadsheets/d/1tGYGCx97DXlaN50xZIgqbM9cjN2Hu5pC0yUwO7KhmUk/edit#gid=156307859
