### ISSUE TITLE
Iniciar desenvolvimento da RF04 e RF05

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/2021.2-Sigaa-Plus#201]
### Descrição:
Iniciar o desenvolvimento das funcionalidades RF04 e RF05 (Gráfico de créditos optativos e módulo livre)

### Tarefas:

- [x] Estudar formas de implementar os gráficos
- [x] Iniciar desenvolvimento dos requisitos 
- [x] Implementar gráfico
- [x] Adicionar textos

### Critérios de aceitação:

- [x] Subir alterações para o repositório
- [x] Revisar funcionamento das funcionalidade implementadas

**Comment by RochaCarla** [comment]
Essa issue está muito grande para uma sprint. Sugestão: quebrar em issues menores e alocar mais uma dupla resolvendo essa questão.

**Comment by eng-Bruno** [comment]
Funcionalidade implementada e esperando pra ser revisada

**Comment by eng-Bruno** [comment]
Video utilizado para estudar como implementar o gráfico: [Youtube](https://www.youtube.com/watch?v=4cMlXcNgKec&ab_channel=Webnoob)
