### ISSUE TITLE
Desenvolvimento inicial da RF03

### ISSUE THREAD

**Issue by Madu01** [fga-eps-mds/2021.2-Sigaa-Plus#205]
### Descrição:

Inicio da criação do gráfico créditos por disciplinas obrigatórias (RF03).

### Tarefas:

- [x]  desenvolver a estrutura inicial do gráfico de barra horizontal.
- [x]  desenvolver a parte inicial da informação do total de créditos por disciplinas obrigatorias logo abaixo do gráfico.
- [x] desenvolver a parte inicial da informação de créditos cursados por disciplinas obrigatorias logo abaixo do gráfico.
- [x] disponibilizar informação de quais das tecnologias foram utilizadas para desenvolver o gráfico.

### Critérios de aceitação:

- [ ] ser revisado.
- [ ] as tecnilogias utilizadas não podem serem diferentes das que estão presentes no documento de arquitetura.

**Comment by Madu01** [comment]
As tecnologias que serão utilizadas para desenvolver o gráfico:
VueChartJS - (Vue)
HTML
CSS
JavaScript

**Comment by EduardaSMarques** [comment]
Foi decidido que amanhã 22/03/2022 terá uma reunião às 16:00h para iniciar a elaboração do gráfico

**Comment by Madu01** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/205?planning-poker) with ZenHub @beatrizSO

**Comment by Madu01** [comment]
- Foi decidido que a tecnologia VueChart não será implementada em por enquanto. 
- Criamos o grafico utilizando o style e o templete do Vue que correspondem respectivamente ao CSS e ao HTML. Fizemos dessa forma, pois descobrimos que fica mais viável a manipulação do gráfico, da pra edita-lo no formato e cores iguais ao do prototipo de alta fidelidade.
