### ISSUE TITLE
Criar novo protótipo (visão do google)

### ISSUE THREAD

**Issue by beatrizSO** [fga-eps-mds/2021.2-Sigaa-Plus#206]
### Descrição:
Criar protótipo explicitando a visão da extensão no google e o pop-up apresentado

### Tarefas:

- [x]  Criar o protótipo de forma coerente com o projeto e a estrutura definida;

### Critérios de aceitação:
- [ ] Protótipo revisado e de acordo com o esperado;

**Comment by beatrizSO** [comment]
@EduardaSMarques pode revisar para mim?

**Comment by EduardaSMarques** [comment]
Protótipo revisado e tudo dentro do esperado!
