### ISSUE TITLE
Planning sprint 10 - Time A

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#222]
### Descrição:
Documento de planejamento da sprint 10

### Tarefas:

- [x]  Criar documento

### Critérios de aceitação:

- [x] O documento deve ser revisado

**Comment by laisramos123** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/222?planning-poker) with ZenHub @HianPraxedes
