### ISSUE TITLE
Suporte ao front-end para a criação de componentes visuais referentes à RF01.

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#225]
### Descrição:
Suporte do Time A para o Time B.

### Tarefas:

- [ ]  Integrantes do time A devem dar o suporte necessário para o time B para a criação dos componentes visuais relativos a RF01

### Critérios de aceitação:
- [ ] Os componentes visuais devem estar prontos

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/225?planning-poker) with ZenHub @ahbreu @beatrizSO

**Comment by laisramos123** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/225?planning-poker) with ZenHub @EduardaSMarques
