### ISSUE TITLE
Suporte ao front-end para a criação de componentes visuais referentes à RF02.

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#226]
### Descrição:
Suporte do Time A para o Time B e a criação dos componentes visuais da RF2

### Tarefas:

- [x]  Integrantes do time A devem dar o suporte necessário para o time B para a criação dos componentes visuais relativos a RF02
- [x] Criação dos componentes visuais relativos a RF2

### Critérios de aceitação:
- [x] Os componentes visuais devem estar prontos

**Comment by Madu01** [comment]
- Componente visual concluído! ficou assim:

![tabelas](https://user-images.githubusercontent.com/64814266/161170748-c4b8cae1-c936-4b47-9389-be04370ae238.jpg)

- Agora falta fazer com que o componente visual consuma os dados da api para aparecer as disciplinas conforme o protótipo de alta fidelidade (imagem logo abaixo):

![tabelasPrototipo](https://user-images.githubusercontent.com/64814266/161171006-a61ae005-8e93-40ad-bb24-cfe9f6148f7b.jpg)

**Comment by Madu01** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/226?planning-poker) with ZenHub @GabriellyAssuncao @HianPraxedes
