### ISSUE TITLE
Integração do Back-end e do Front-end da RF01.

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#227]
### Descrição:
Realizar a integração do back-end e do front-end em relação a RF01.

### Tarefas:

- [x]  Fazer com que o componentes visuais consuma os dados da api.
     - [x]  Consumir os dados das disciplinas no buscador
     - [x]  Consumir dados das disciplinas equivalentes no resultado da busca

### Critérios de aceitação:

- [x] A funcinalidade deve ser revisada
- [x] O pull request deve ser aceito

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/227?planning-poker) with ZenHub @vitormanoel17 @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes

**Comment by laisramos123** [comment]
Foi feito o pareamento na sexta-feira (01/04) com o objetivo de criar a integração da RF01. Dentro disto, buscamos entender o problema para encontrar a melhor solução. Entretanto tivemos alguns empecilhos na impressão dos dados que estão sendo capturados a partir da api . E ficarão pendentes para serem resolvidos posteriormente.
