### ISSUE TITLE
Integração do Back-end e do Front-end da RF02.

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#228]
### Descrição:
Realizar a integração do back-end e do front-end em relação a RF02.

### Tarefas:

- [x]  Fazer com que o componentes visuais consuma os dados da api.
     - [x]  Criar lista com matérias já cursadas pelo aluno. @GabriellyAssuncao 
     - [x]  Criar lista com matérias que aluno já pode cursar no próximo semestre. @Madu01 @HianPraxedes 

### Critérios de aceitação:

- [x] A funcinalidade deve ser revisada
- [x] O pull request deve ser aceito

**Comment by Madu01** [comment]
Foi feito uma reunião hoje e foi decidido o que cada um do trio irá fazer
- Criar lista com matérias já cursadas pelo aluno. Responsável: @GabriellyAssuncao
- Criar lista com matérias que aluno já pode cursar no próximo semestre. Responsável: @Madu01
- Separa entre optativas e obrigatórias. Responsável: @HianPraxedes

**Comment by GabriellyAssuncao** [comment]
Galera, vamos compartilhar aqui vídeo-aulas e links de documentações que ajudem na integração.

**Comment by Madu01** [comment]
Achei esse link interessante pra poder criar as listas : https://www.youtube.com/watch?v=zyytxlMzB4A

**Comment by GabriellyAssuncao** [comment]
Utilização do localStorage:
https://www.youtube.com/watch?v=hNTozXl-qJA
https://www.youtube.com/watch?v=6deCUoDuMQc
https://www.youtube.com/watch?v=zmuP_2qmWfE
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by vitormanoel17** [comment]
Após reunião no discord, eu @vitormanoel17 e  @HianPraxedes  conseguimos resolver as pendências relacionadas a RF02, conseguindo consumir a API e apresentar os dados relacionados a matérias cursadas e não cursadas pelo usuário.
