### ISSUE TITLE
Resumo Sprint 11 - Time A

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#242]
### Descrição:
Adicionar issues references ás tarefas da sprint 11.

### Tarefas:
- [x] #244
- [ ] #227
- [ ] #228
- [ ] #245
- [ ] #246
- [x] #247

### Critérios de aceitação:

- [ ] Todas as issues devem estar concluídas

**Comment by laisramos123** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/242?planning-poker) with ZenHub @GabriellyAssuncao

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/242?planning-poker) with ZenHub @ahbreu @Elios630 @HianPraxedes @vitormanoel17

**Comment by laisramos123** [comment]
O time não conseguiu entregar todas as tarefas estipuladas, portanto as tarefas não terminadas serão realocadas para a próxima Sprint, no caso a 12, causando acúmulo de trabalho. O time deverá se reorganizar para entregar todas as tarefas da próxima vez.
