### ISSUE TITLE
Qualidade de sotfware

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#246]
### Descrição:
Determinar qualidade de software: SIGAA+

### Tarefas:

- [x] Aprender sobre qualidade de software
- [x] Usar softwares para a medição da qualidade de software do nosso produto

### Critérios de aceitação:

- [ ] Documentação acerca da qualidade

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/246?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by laisramos123** [comment]
Estou tendo dificuldade para fazer a medição através do Sonar Clound, pois para fazer a medição preciso ser proprietária do repositório.

**Comment by laisramos123** [comment]
Para a análise da qualidade final, como estava tendo problemas com o SonarClound, utilizei a plataforma Embold e segue alguns indicadores de qualidade coletados na analise:
![Captura de tela de 2022-04-23 08-43-40](https://user-images.githubusercontent.com/38669960/164893113-4360c3a7-2795-4a17-9e40-b3c9a7ff6356.png)
 Para mais informações, acessar o documento de qualidade de software que está junto à documentação do projeto.

**Comment by laisramos123** [comment]
Utilizei também a ferramenta Code Climate para averiguar informações acerca do Débito técnico, da relação *Churn vs. maintainability* e sobre o progresso da criação de novas linhas de código.
