### ISSUE TITLE
Produção dos vídeos - vídeo do projeto e vídeo do Time A

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#264]
### Descrição:
Produção e edição dos videos referentes à entrega da Release 02. O primeiro deverá ser um vídeo para "vender" o nosso produto e deverá ser produzido pelos dois times. O segundo deverá ser produzido pelo Time A e será um relato de cada membro sobre a sua experiência em cada etapa do projeto.

### Tarefas:

- [x] Produção do vídeo do Projeto
- [x] Edição do vídeo do Projeto
- [x] Produção do Vídeo do Time A
- [x] Edição do vídeo - Time A
- [x] Produção do Vídeo do Time B
- [x] Edição do vídeo - Time B

### Critérios de aceitação:

- [x] Os vídeos devem ser editados.
- [x] Todos os vídeos devem ser revisados.

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/264?planning-poker) with ZenHub @beatrizSO @EduardaSMarques @eng-Bruno @LuizPettengill @Madu01 @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17

**Comment by HianPraxedes** [comment]
Link dos vídeos:
https://drive.google.com/drive/folders/10QlrjWGwB_-uqGuZTFg2VXWr6vSjq2jl?usp=sharing
