### ISSUE TITLE
Fazer o empacotamento do software como extensão

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#267]
### Descrição:
Empacotamento do software como extensão

### Tarefas:

- [x] Realizar o empacotamento do software como uma extensão
- [x] Testar componentes visuais na página do SIGAA
- [x] Realizar integração da RF02 dentro da extensão

### Critérios de aceitação:

- [x] Pull Request Revisado e aceito

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/267?planning-poker) with ZenHub @ahbreu @Elios630 @GabriellyAssuncao @HianPraxedes @vitormanoel17 @beatrizSO @EduardaSMarques @eng-Bruno @LuizPettengill @Madu01

**Comment by vitormanoel17** [comment]
Empacotamento dos componentes vue é realizado pelo comando ```npm run build```. É necessário que os componentes estejam corretamente proporcionais ao site do sigaa.  Partindo disso temos que realizar o redimensionamento dos componentes para que estes sejam inseridos de forma correta, fazendo também as devidas manipulações no DOM.

![image](https://user-images.githubusercontent.com/74791849/164296167-85e8cb1d-50f1-42a7-bf5f-c8e8c590ba06.png)

**Comment by vitormanoel17** [comment]
![image](https://user-images.githubusercontent.com/74791849/164995833-f52a2776-f207-4a0d-a783-32f300d87127.png)
Componentes ajustados na página do SIGAA conforme o esperado. Ajustes ainda são necessários, porém aplicação já está integrada
