### ISSUE TITLE
Dar suporte ao time B quanto à finalização do front-end da RF02

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/2021.2-Sigaa-Plus#268]
Dar suporte à @Madu01 , @beatrizSO e @EduardaSMarques  na parte do front-end da RF02
### Tarefas:

- [x] Auxiliar na produção da RF02
- [x] Finalização da parte do front-end da RF02

### Critérios de aceitação:

- [x] Pull request aceito

**Comment by laisramos123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tema-02-61fbe43eee3f2e001039033f/issues/fga-eps-mds/2021.2-Sigaa-Plus/268?planning-poker) with ZenHub @ahbreu @beatrizSO @EduardaSMarques @Elios630 @eng-Bruno @GabriellyAssuncao @HianPraxedes @LuizPettengill @Madu01 @vitormanoel17

**Comment by vitormanoel17** [comment]
Os Componentes relacionados a RF02 já estão integrados com a página do SIGAA, resta apresentar os dados relacionados ao fluxo de matérias nos mesmos.
