### ISSUE TITLE
Dropdown de navegação

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#272]
### Descrição:

Desenvolver dropdown de navegação entre páginas do plugin.

### Tarefas:

- [x] Desenvolvimento visual do dropdown
- [x] Desenvolvimento funcional do dropdown

### Critérios de aceitação:
- [x] Pull request revisado e aceito

**Comment by eng-Bruno** [comment]
parte funcional do dropdown completa, só falta fazer a estilização do mesmo
