### ISSUE TITLE
Correção componentes visuais

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/2021.2-Sigaa-Plus#274]
### Descrição:
Corrigir o estilo dos componentes visuais referentes à RF02.
### Tarefas:

- [x]  Ajustar tamanho dos componentes em relação á página do SIGAA

### Critérios de aceitação:

- [x] Pull request revisado e aceito

**Comment by GabriellyAssuncao** [comment]
Os componentes da RF02 foram refatorados para se ajustarem na página do SIGAA. Pull request sujeito à revisão. @vitormanoel17

**Comment by vitormanoel17** [comment]
Pull request revisado, solicitado modificações.

**Comment by GabriellyAssuncao** [comment]
Concluídas as modificações solicitadas.
