### ISSUE TITLE
Planejamento Sprint 13 - Time B

### ISSUE THREAD

**Issue by LuizPettengill** [fga-eps-mds/2021.2-Sigaa-Plus#278]
### Descrição:
Sprint com o objetivo de terminar os tópicos pendentes para a entrega da Release 02. Para isso o time deverá cumprir as tarefas atrasadas e cumprir as tarefas próprias da Sprint 13. Também daremos suporte ao time B para entregar todas as funcionalidades previstas da extensão.

### Tarefas:
- [x] #245 
- [x] #246 
- [x] #262
- [x] #263
- [x] #264
- [x] #265

### Critérios de aceitação:
- [x] Todas as issues devem ser concluídas.

**Comment by eng-Bruno** [comment]
Documento disponível em [Planejamento - Sprint 13](https://github.com/fga-eps-mds/2021.2-Sigaa-Plus/blob/main/docs/sprints/sprint13/TimeB/Planejamento.md)
