### ISSUE TITLE
Correção do protótipo de alta qualidade

### ISSUE THREAD

**Issue by EduardaSMarques** [fga-eps-mds/2021.2-Sigaa-Plus#282]
### Descrição:
Correção de algumas telas do protótipo de alta qualidade

### Tarefas:

- [x]  Corrigir a tela 3.1.3 
- [x]  Corrigir a cor do checkbox da tela 3.1.4

### Critérios de aceitação:

- [x] Pull request deve ser revisado e aceito

**Comment by Madu01** [comment]
já revisei! corrigiram os textos e as imagens estão ok sem problemas!
