### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by EduardaSMarques** [fga-eps-mds/2021.2-Sigaa-Plus#74]
### Descrição:
Criar o protótipo de baixa fidelidade do projeto 

### Tarefas:

- [x]  Decidir qual ferramenta será usada na criação do protótipo 
- [x]  Decidir a disposição do plugin na tela do SIGAA
- [x] Fazer um Documento  com o protótipo e explicando as telas  

### Critérios de aceitação:

- [x] Protótipo deve ser revisado 
- [x] Protótipo deve ter todas as funções sugeridas para o projeto

**Comment by EduardaSMarques** [comment]
Protótipo feito no Jamboard:
https://jamboard.google.com/d/1ZfAj8pm_QTHrd6XwLe9oX2dpqc3AtgFuCnjfIxBTzM0/edit?usp=sharing

**Comment by beatrizSO** [comment]
Revião realizada dia 24/02/22.

Protótipo de baixa fidelidade de acordo com a proposta e incluindo todas as funcionalidades definidas para projeto.

**Comment by ahbreu** [comment]
![Group 1](https://user-images.githubusercontent.com/56367128/155624936-c46cac8b-0957-4099-87e9-c6ef72021278.png)

**Comment by ahbreu** [comment]
![Group 2](https://user-images.githubusercontent.com/56367128/155624959-48ca2148-dadd-4d0a-952d-d82cc942ff91.png)

**Comment by ahbreu** [comment]
![Group 3](https://user-images.githubusercontent.com/56367128/155624977-f77e136c-525f-48e2-b3e5-11ce75277fe6.png)

**Comment by ahbreu** [comment]
![Group 4](https://user-images.githubusercontent.com/56367128/155624990-36530164-a1e5-4b28-8adc-9c20b60b96ea.png)

**Comment by ahbreu** [comment]
![Group 5](https://user-images.githubusercontent.com/56367128/155625008-b587be03-128b-4ed5-bff2-1b1e683a887a.png)

**Comment by ahbreu** [comment]
Link para o protótipo de baixa fidelidade:

https://www.figma.com/file/0cItStyTdqlQQzvB0TiH7s/Untitled?node-id=0%3A1
